name: 'container action type'
description: 'action template'
author: 'Soul Craters'
inputs:
  myInput:
    description: 'first line'
    required: true
    default: 'default first line'
outputs:
  myOutput:
    description: 'current total memory in container'
runs:
  using: 'docker'
  image: 'Dockerfile'
